-- Load plugin modules in a predictable order.
require("plugins.mini")
require("plugins.colorscheme")
require("plugins.fzf-lua")
require("plugins.servery")
require("plugins.live-preview")
require("plugins.diffs")
require("plugins.fugitive")
require("plugins.nb")
require("plugins.treesitter")
require("plugins.dap")
require("plugins.vim-test")
require("plugins.easy-dotnet")
